version: 2.1
orbs:
  codecov: codecov/codecov@3.2.4
  sonarcloud: sonarsource/sonarcloud@1.1.1

jobs:
  build:
    docker:
      - image: cimg/openjdk:18.0.2
    steps:
      - checkout
      - run:
          name: Install dependencies, run tests, and collect coverage
          command: gradle build test
      - codecov/upload
      - sonarcloud/scan

workflow:
  build-test-scan:
    jobs:
      - build:
          context: SonarCloud
